apiVersion: v1
kind: Service
metadata:
  name: avalanches-app-loadbalancer
  labels:
    app: avalanches
spec:
  type: LoadBalancer
  ports:
    - port: 80           # Porta externa
      targetPort: 8080    # Porta onde sua aplicação está rodando
  selector:
    app: avalanches
