apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedido-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pedido
  template:
    metadata:
      labels:
        app: pedido
    spec:
      containers:
        - name: pedido
          image: 307946636040.dkr.ecr.sa-east-1.amazonaws.com/ms-pedido:latest
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: "300m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
          # Adição de variáveis de ambiente
          env:
            - name: DATABASE_DIALECT
              value: "postgres"
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: pedido-dbcredentials
                  key: host
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: pedido-dbcredentials
                  key: port
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pedido-dbcredentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pedido-dbcredentials
                  key: password
            - name: POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: pedido-dbcredentials
                  key: db
            - name: TYPEORM_CONNECTION
              value: "postgres"
            - name: TYPEORM_URL
              valueFrom:
                secretKeyRef:
                  name: pedido-dbcredentials
                  key: typeorm
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: pedido-dbcredentials
                  key: redis_host
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: pedido-dbcredentials
                  key: redis_port
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pedido-dbcredentials
                  key: redis_password
